"""Public service boundaries for DeepInsight Phase One."""

from src.services.data_ingestion import (
    DataIngestionService,
    IngestionRequest,
    IngestionRunError,
)
from src.services.data_normalization import (
    AssetIdentifierNormalizer,
    DataNormalizer,
    NormalizationError,
    NormalizedDocument,
)
from src.services.document_embedding import (
    DocumentEmbeddingConsistencyError,
    DocumentEmbeddingError,
    DocumentEmbeddingService,
)
from src.services.document_processing import (
    DocumentChunker,
    HashVectorIdAllocator,
    RawTextStore,
    VectorIdAllocator,
)
from src.services.embedding import (
    EmbeddingConfigurationError,
    EmbeddingInputError,
    EmbeddingRemoteError,
    EmbeddingService,
    EmbeddingServiceError,
    FakeEmbeddingService,
    OpenAIEmbeddingService,
    QwenEmbeddingService,
)
from src.services.golden_replay import (
    GoldenReplayError,
    GoldenReplayInput,
    GoldenReplayLeakageFixture,
    GoldenReplayService,
    validate_leakage_challenges,
)
from src.services.llm_gateway import (
    LLMCache,
    LLMCacheError,
    LLMCacheReliabilityPolicy,
    LLMFailureMetadata,
    LLMFailureMetadataSink,
    LLMGateway,
    LLMMetadataError,
    LLMRunMetadata,
    LLMRunMetadataSink,
    LLMRunResult,
    LLMSchemaValidationError,
    LLMSingleFlight,
)
from src.services.llm_provider import (
    ConfiguredLLMProvider,
    CredentialNotConfigured,
    FakeLLMProvider,
    LLMAuthenticationError,
    LLMConfigurationError,
    LLMConnectionError,
    LLMInvalidJSONError,
    LLMInvalidRequestError,
    LLMInvalidResponseError,
    LLMProvider,
    LLMProviderCall,
    LLMProviderCapabilities,
    LLMProviderError,
    LLMProviderResult,
    LLMRateLimitError,
    LLMRemoteError,
    LLMTimeoutError,
    OpenAIProvider,
    QwenProvider,
    build_configured_llm_provider,
)
from src.services.opportunity import OpportunityCandidateBuilder
from src.services.provider_transport import (
    ProviderTransportConfig,
    resolve_provider_transport_config,
)
from src.services.research_data_bundle import ResearchDataBundleService
from src.services.research_dataset import (
    ResearchDatasetBuilder,
    ResearchDatasetBuildError,
)
from src.services.research_episode import (
    ResearchEpisodeBuilder,
    ResearchEpisodeBuildError,
)
from src.services.research_quant_handoff import (
    ResearchQuantHandoffBuilder,
    ResearchQuantHandoffBuildError,
    ResearchQuantHandoffExporter,
    ResearchQuantHandoffExportError,
)
from src.services.research_state import ResearchStateBuilder, ResearchStateBuildError
from src.services.research_state_transition import (
    ResearchStateTransitionBuilder,
    ResearchStateTransitionBuildError,
)
from src.services.satellite_alpha import (
    SatelliteAlphaMapper,
    build_satellite_alpha_registry_v1,
    research_state_semantic_support_audit_v1,
)
from src.services.sector_ontology import (
    SectorOntologyService,
    SectorOntologyValidationError,
    build_sector_ontology_seed_v1,
    build_sector_ontology_v1,
    validate_scope_hierarchy,
    validate_sector_ontology_seed,
)
from src.services.sector_radar import SectorRadarMemoryError, SectorRadarMemoryService
from src.services.sector_universe import (
    CURRENT_US_RESEARCH_UNIVERSE_VERSION,
    SectorUniverseError,
    SectorUniverseService,
    build_current_us_research_memberships_v1,
    build_us_sector_benchmark_candidates_v1,
    resolve_validated_benchmark_mappings,
)

__all__ = [
    "AssetIdentifierNormalizer",
    "DataIngestionService",
    "DataNormalizer",
    "DocumentChunker",
    "DocumentEmbeddingConsistencyError",
    "DocumentEmbeddingError",
    "DocumentEmbeddingService",
    "EmbeddingConfigurationError",
    "EmbeddingInputError",
    "EmbeddingRemoteError",
    "EmbeddingService",
    "EmbeddingServiceError",
    "ConfiguredLLMProvider",
    "CURRENT_US_RESEARCH_UNIVERSE_VERSION",
    "CredentialNotConfigured",
    "FakeLLMProvider",
    "FakeEmbeddingService",
    "HashVectorIdAllocator",
    "GoldenReplayError",
    "GoldenReplayInput",
    "GoldenReplayLeakageFixture",
    "GoldenReplayService",
    "IngestionRequest",
    "IngestionRunError",
    "LLMAuthenticationError",
    "LLMCache",
    "LLMCacheError",
    "LLMCacheReliabilityPolicy",
    "LLMConfigurationError",
    "LLMConnectionError",
    "LLMFailureMetadata",
    "LLMFailureMetadataSink",
    "LLMGateway",
    "LLMInvalidRequestError",
    "LLMInvalidJSONError",
    "LLMInvalidResponseError",
    "LLMMetadataError",
    "LLMProvider",
    "LLMProviderCapabilities",
    "LLMProviderCall",
    "LLMProviderError",
    "LLMProviderResult",
    "LLMRateLimitError",
    "LLMRemoteError",
    "LLMRunMetadata",
    "LLMRunMetadataSink",
    "LLMRunResult",
    "LLMSchemaValidationError",
    "LLMSingleFlight",
    "LLMTimeoutError",
    "NormalizationError",
    "NormalizedDocument",
    "OpportunityCandidateBuilder",
    "OpenAIProvider",
    "OpenAIEmbeddingService",
    "ProviderTransportConfig",
    "QwenEmbeddingService",
    "QwenProvider",
    "RawTextStore",
    "ResearchDataBundleService",
    "ResearchDatasetBuilder",
    "ResearchDatasetBuildError",
    "ResearchEpisodeBuildError",
    "ResearchEpisodeBuilder",
    "ResearchQuantHandoffBuilder",
    "ResearchQuantHandoffBuildError",
    "ResearchQuantHandoffExporter",
    "ResearchQuantHandoffExportError",
    "ResearchStateBuildError",
    "ResearchStateBuilder",
    "ResearchStateTransitionBuildError",
    "ResearchStateTransitionBuilder",
    "SatelliteAlphaMapper",
    "SectorOntologyService",
    "SectorOntologyValidationError",
    "SectorRadarMemoryError",
    "SectorRadarMemoryService",
    "SectorUniverseError",
    "SectorUniverseService",
    "VectorIdAllocator",
    "build_configured_llm_provider",
    "build_satellite_alpha_registry_v1",
    "build_sector_ontology_seed_v1",
    "build_sector_ontology_v1",
    "build_current_us_research_memberships_v1",
    "build_us_sector_benchmark_candidates_v1",
    "resolve_validated_benchmark_mappings",
    "resolve_provider_transport_config",
    "validate_scope_hierarchy",
    "validate_sector_ontology_seed",
    "validate_leakage_challenges",
    "research_state_semantic_support_audit_v1",
]
