"""Public Phase One data contracts."""

from src.schemas.agents import (
    AgentContext,
    AgentRequest,
    AnalystAnalysis,
    AnalystOutput,
    AnalystResponse,
    BearManagerRequest,
    BearManagerResponse,
    BullManagerRequest,
    BullManagerResponse,
    FundamentalAnalysis,
    FundamentalAnalystResponse,
    ResearchManagerRequest,
    ResearchManagerResponse,
    ResearchSummary,
    RiskManagerRequest,
    RiskManagerResponse,
)
from src.schemas.common import ErrorInfo, SourceReference, TaskStatusResponse
from src.schemas.documents import (
    DocumentChunkRecord,
    RetrievedDocument,
    TextDocumentRecord,
)
from src.schemas.llm import LLMRequest, LLMResponse, LLMUsage
from src.schemas.market_data import (
    CorporateEventRecord,
    EodBarRecord,
    FundamentalRecord,
    InstrumentRecord,
    MacroObservationRecord,
    RawDataRecord,
)
from src.schemas.memory import (
    MemorySearchRequest,
    MemorySearchResponse,
    MemorySearchResult,
    MemoryWriteRequest,
    MemoryWriteResult,
)
from src.schemas.reports import GenerateReportRequest, ReportSection, ResearchReport

__all__ = [
    "AgentContext",
    "AgentRequest",
    "AnalystAnalysis",
    "AnalystOutput",
    "AnalystResponse",
    "BearManagerRequest",
    "BearManagerResponse",
    "BullManagerRequest",
    "BullManagerResponse",
    "CorporateEventRecord",
    "DocumentChunkRecord",
    "EodBarRecord",
    "ErrorInfo",
    "FundamentalAnalysis",
    "FundamentalAnalystResponse",
    "FundamentalRecord",
    "GenerateReportRequest",
    "InstrumentRecord",
    "LLMRequest",
    "LLMResponse",
    "LLMUsage",
    "MacroObservationRecord",
    "MemorySearchRequest",
    "MemorySearchResponse",
    "MemorySearchResult",
    "MemoryWriteRequest",
    "MemoryWriteResult",
    "RawDataRecord",
    "ReportSection",
    "ResearchManagerRequest",
    "ResearchManagerResponse",
    "ResearchReport",
    "ResearchSummary",
    "RetrievedDocument",
    "RiskManagerRequest",
    "RiskManagerResponse",
    "SourceReference",
    "TaskStatusResponse",
    "TextDocumentRecord",
]
